version: "3.9"

services:
  mcp-server:
    build: ./server
    container_name: mcp-server
    ports:
      - "8001:8001"
    env_file:
      - .env
    restart: always

  streamlit-ui:
    build: ./client
    container_name: streamlit-ui
    ports:
      - "8501:8501"
    environment:
      - SERVER_URL=http://mcp-server:8001/mcp/sse
    env_file:
      - .env
    depends_on:
      - mcp-server
    restart: always
